baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10

[params]
contentTypeName = "posts"
defaultTheme = "light"
showMenuItems = 2
showReadingTime = false
description = "Adrien Pailhes's website and blog."
keywords = "homepage, blog"

[params.portrait]
path = "/images/avatar.jpg"
maxWidth = "200px"

[[params.social]]
name = "twitter"
url = "https://twitter.com/adrienpailhes"

[[params.social]]
name = "github"
url = "https://github.com/adioss"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/apailhes/"

#[[params.social]]
#name = "dev"
#url = "https://dev.to/adioss/"

#[[params.social]]
#name = "medium"
#url  = "https://medium.com/@apailhes/"


[languages]
[languages.en]
title = "Adrien PAILHES"
subtitle = "Developer – Application Security Engineer"
homeSubtitle = "Developer – Application Security Engineer"
keywords = "developer,security,appsec,redteam"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
# leave empty to disable, enter display text to enable
# lastModDisplay = ""

[languages.en.params.logo]
logoText = "alias cd='rm -rf'"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 1
[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 2
